## Google Colab test

# Tensor Basic

In [1]:
import torch
print(torch.cuda.is_available())
print(torch.rand(2,2))

False
tensor([[0.9480, 0.4534],
        [0.1148, 0.8286]])


In [2]:
# Tensors
x = torch.tensor([[0,0,1], [1,1,1], [0,0,0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [3]:
# Change value of tensor
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [4]:
# using zeros & ones
print(torch.zeros(2,2))
print(torch.ones(1,2))
print(torch.ones(1,2) + torch.ones(1,2))

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.]])
tensor([[2., 2.]])


In [5]:
# get value of rank0
print(torch.rand(1).item())
print(type(torch.rand(1).item()))
print(x[0][0].item())
print(type(x[0][0]))
print(type(x[0][0].item()))

0.3224375247955322
<class 'float'>
5
<class 'torch.Tensor'>
<class 'int'>


In [6]:
# using gpu
cpu_tensor = torch.rand(2)
print(cpu_tensor.device)

# gpu_tensor = cpu_tensor.to("cuda") # must fail without gpu
# print(gpu_tensor.device)

print(cpu_tensor)
# print(gpu_tensor)

cpu_tensor = torch.rand(2)
print(cpu_tensor)
# print(gpu_tensor)

cpu
tensor([0.1778, 0.1432])
tensor([0.6646, 0.5490])


## Tensor Operations

In [7]:
# get max value of tensor
a = torch.rand(2,2)
print(a)
print(a.max())
print(a.max().item())

tensor([[0.4768, 0.2670],
        [0.5984, 0.2894]])
tensor(0.5984)
0.5983900427818298


In [8]:
# convert tensor type
long_tensor = torch.tensor([[0,0,1], [0,1,0], [1,0,0]])
print(type(long_tensor))
print(long_tensor.type())
print(long_tensor)

float_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]]).to(dtype=torch.float32)
print(float_tensor.type())
print(float_tensor)

<class 'torch.Tensor'>
torch.LongTensor
tensor([[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]])
torch.FloatTensor
tensor([[0., 0., 1.],
        [1., 1., 1.],
        [0., 0., 0.]])


In [9]:
# in-place operation with _
a = torch.rand(2,2)
print(a)
print(a.log2())  # new tensor is return
print(a)
print(a.log2_()) # in-place update with _
print(a)

tensor([[0.5158, 0.5292],
        [0.7255, 0.5891]])
tensor([[-0.9552, -0.9180],
        [-0.4630, -0.7634]])
tensor([[0.5158, 0.5292],
        [0.7255, 0.5891]])
tensor([[-0.9552, -0.9180],
        [-0.4630, -0.7634]])
tensor([[-0.9552, -0.9180],
        [-0.4630, -0.7634]])


In [10]:
# reshape tensor
flat_tensor = torch.rand(28 * 28)
print(flat_tensor.shape)
print(flat_tensor.size())

viewed_tensor = flat_tensor.view(1,28,28)
print(viewed_tensor.shape)
print(viewed_tensor[0][0])

reshaped_tensor = flat_tensor.reshape(1,28,28)
print(reshaped_tensor.shape)
print(reshaped_tensor[0][0])

flat_tensor[0] = 44
print(flat_tensor[0])
print(viewed_tensor[0][0][0])
print(reshaped_tensor[0][0][0])

torch.Size([784])
torch.Size([784])
torch.Size([1, 28, 28])
tensor([0.5952, 0.8111, 0.7891, 0.7171, 0.7734, 0.5779, 0.4158, 0.9934, 0.1987,
        0.6993, 0.0828, 0.3646, 0.0065, 0.4439, 0.9448, 0.7222, 0.7886, 0.9632,
        0.5424, 0.4507, 0.4189, 0.5099, 0.5450, 0.4108, 0.4461, 0.3561, 0.6549,
        0.1428])
torch.Size([1, 28, 28])
tensor([0.5952, 0.8111, 0.7891, 0.7171, 0.7734, 0.5779, 0.4158, 0.9934, 0.1987,
        0.6993, 0.0828, 0.3646, 0.0065, 0.4439, 0.9448, 0.7222, 0.7886, 0.9632,
        0.5424, 0.4507, 0.4189, 0.5099, 0.5450, 0.4108, 0.4461, 0.3561, 0.6549,
        0.1428])
tensor(44.)
tensor(44.)
tensor(44.)


In [11]:
# rearrange the dimension
hwc_tensor = torch.rand(640, 480, 3) # Width, Height, Channel
chw_tensor = hwc_tensor.permute(2, 0, 1) # permute to Channel x W x H
print(chw_tensor.shape)

torch.Size([3, 640, 480])


In [12]:
# tensor broadcasting
a = torch.tensor([[1,1,1], [2,2,2], [3,3,3]])
print(a)
b = torch.tensor([[4,4], [5,5]])
print(b)
# print (a + b) # occur exception
c = torch.tensor([6,6,6])
print(a + c) # brocasting with 1x3
d = torch.tensor([[6], [7], [8]])
print(a + d) # broadcasting with 3x1



tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
tensor([[4, 4],
        [5, 5]])
tensor([[7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])
tensor([[ 7,  7,  7],
        [ 9,  9,  9],
        [11, 11, 11]])
